export const countries = [
  { id: 1, value: '', label: 'All Countries' },
  { id: 2, value: 'ar', label: 'Argentina' },
  { id: 3, value: 'au', label: 'Australia' },
  { id: 4, value: 'at', label: 'Austria' },
  { id: 5, value: 'be', label: 'Belgium' },
  { id: 6, value: 'br', label: 'Brazil' },
  { id: 7, value: 'bg', label: 'Bulgaria' },
  { id: 8, value: 'ca', label: 'Canada' },
  { id: 9, value: 'cn', label: 'China' },
  { id: 10, value: 'co', label: 'Colombia' },
  { id: 11, value: 'cu', label: 'Cuba' },
  { id: 12, value: 'cz', label: 'Czech Republic' },
  { id: 13, value: 'eg', label: 'Egypt' },
  { id: 14, value: 'fr', label: 'France' },
  { id: 15, value: 'de', label: 'Germany' },
  { id: 16, value: 'gr', label: 'Greece' },
  { id: 17, value: 'hk', label: 'Hong Kong' },
  { id: 18, value: 'hu', label: 'Hungary' },
  { id: 19, value: 'in', label: 'India' },
  { id: 20, value: 'id', label: 'Indonesia' },
  { id: 21, value: 'ie', label: 'Ireland' },
  { id: 22, value: 'il', label: 'Israel' },
  { id: 23, value: 'it', label: 'Italy' },
  { id: 24, value: 'jp', label: 'Japan' },
  { id: 25, value: 'lv', label: 'Latvia' },
  { id: 26, value: 'lt', label: 'Lithuania' },
  { id: 27, value: 'my', label: 'Malaysia' },
  { id: 28, value: 'mx', label: 'Mexico' },
  { id: 29, value: 'ma', label: 'Morocco' },
  { id: 30, value: 'nl', label: 'Netherlands' },
  { id: 31, value: 'nz', label: 'New Zealand' },
  { id: 32, value: 'ng', label: 'Nigeria' },
  { id: 33, value: 'no', label: 'Norway' },
  { id: 34, value: 'ph', label: 'Philippines' },
  { id: 35, value: 'pl', label: 'Poland' },
  { id: 36, value: 'pt', label: 'Portugal' },
  { id: 37, value: 'ro', label: 'Romania' },
  { id: 38, value: 'ru', label: 'Russia' },
  { id: 39, value: 'sa', label: 'Saudi Arabia' },
  { id: 40, value: 'rs', label: 'Serbia' },
  { id: 41, value: 'sg', label: 'Singapore' },
  { id: 42, value: 'sk', label: 'Slovakia' },
  { id: 43, value: 'si', label: 'Slovenia' },
  { id: 44, value: 'za', label: 'South Africa' },
  { id: 45, value: 'kr', label: 'South Korea' },
  { id: 46, value: 'se', label: 'Sweden' },
  { id: 47, value: 'ch', label: 'Switzerland' },
  { id: 48, value: 'tw', label: 'Taiwan' },
  { id: 49, value: 'th', label: 'Thailand' },
  { id: 50, value: 'tr', label: 'Turkey' },
  { id: 51, value: 'ae', label: 'UAE' },
  { id: 52, value: 'ua', label: 'Ukraine' },
  { id: 53, value: 'gb', label: 'United Kingdom' },
  { id: 54, value: 'us', label: 'United States' },
  { id: 55, value: 've', label: 'Venuzuela' }
]

export const languages = [
  { id: 1, value: '', label: 'All Lanuages' },
  { id: 2, value: 'ar', label: 'Arabic' },
  { id: 3, value: 'de', label: 'German/Deutsch' },
  { id: 4, value: 'en', label: 'English' },
  { id: 5, value: 'es', label: 'Spanish/Castilian' },
  { id: 6, value: 'fr', label: 'French/français' },
  { id: 7, value: 'he', label: 'Hebrew' },
  { id: 8, value: 'it', label: 'Lithuanian' },
  { id: 9, value: 'nl', label: 'Dutch/Flemish' },
  { id: 10, value: 'no', label: 'Norwegian' },
  { id: 11, value: 'pt', label: 'Portuguese' },
  { id: 12, value: 'ru', label: 'Russian' },
  { id: 13, value: 'sv', label: 'Swedish' },
  { id: 14, value: 'ud', label: 'Urdu' },
  { id: 15, value: 'zh', label: 'Chinese' }
]

export const sortBy = [
  { id: 1, label: 'PublishedAt', value: 'publishedAt' },
  { id: 2, label: 'Popularity', value: 'popularity' },
  { id: 3, label: 'Relevancy', value: 'relevancy' }
]

export const categories = [
  { id: 1, label: 'General', value: 'general' },
  { id: 2, label: 'Business', value: 'business' },
  { id: 3, label: 'Entertainment', value: 'entertainment' },
  { id: 4, label: 'Health', value: 'health' },
  { id: 5, label: 'Science', value: 'science' },
  { id: 6, label: 'Sports', value: 'sports' },
  { id: 7, label: 'Technology', value: 'technology' }
]
